# Docker Compose Override for Local Development
#
# This file is automatically merged with docker-compose.yaml by Docker Compose.
# It overrides the 'image:' directives to use local builds instead of published images.
#
# Usage:
#   docker compose up --build -d    # Build and run locally
#   docker compose up -d            # Use published images (if you comment out this file)
#
# For quick start users: This file is optional and can be ignored.
# For developers: This allows building and testing locally before pushing to CI.

services:
  api:
    build: ./api
    environment:
      # Development mode - enables demo users and relaxed security
      NODE_ENV: development
      # Email configuration for testing with Mailpit
      EMAIL_PROVIDER: smtp
      EMAIL_FROM: noreply@pulsestage.local
      EMAIL_FROM_NAME: PulseStage (Dev)
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_SECURE: "false"
      SMTP_USER: ""
      SMTP_PASS: ""
      FRONTEND_URL: http://localhost:5173
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      # Content Moderation (optional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
  
  web:
    build: ./web

