site_name: PulseStage Documentation
site_url: https://seanmdalton.github.io/pulsestage/
site_description: Open-source Q&A platform for town halls and all-hands meetings
site_author: Sean Dalton
repo_url: https://github.com/seanmdalton/pulsestage
repo_name: seanmdalton/pulsestage
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Light mode - PulseStage blue
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant         # Instant loading
    - navigation.instant.progress # Progress indicator
    - navigation.tracking        # URL updates with scroll
    - navigation.tabs           # Top-level tabs
    - navigation.tabs.sticky    # Sticky tabs
    - navigation.sections       # Collapsible sections (accordion style)
    - navigation.expand         # Expand all sections by default
    - navigation.path           # Show breadcrumb path
    - navigation.top            # Back to top button
    - navigation.indexes        # Section index pages
    - navigation.footer         # Previous/next footer
    - toc.follow               # TOC follows scroll
    - toc.integrate            # Integrate TOC into nav
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search terms
    - search.share            # Share search results
    - content.code.copy       # Copy button for code blocks
    - content.code.annotate   # Code annotations
    - content.tabs.link       # Link content tabs
    - content.tooltips        # Improved tooltips
  icon:
    repo: fontawesome/brands/github
  logo: assets/pulsestage-icon-light.svg
  favicon: assets/favicon.ico
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seanmdalton/pulsestage
      name: PulseStage on GitHub
  version:
    provider: mike
  generator: false  # Remove "Made with Material for MkDocs"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/quick-start.md
      - getting-started/installation.md
      - getting-started/configuration.md
      - getting-started/first-steps.md
      - getting-started/troubleshooting.md
  - User Guide:
      - user-guide/overview.md
      - Basic Features:
          - user-guide/submitting-questions.md
          - user-guide/upvoting.md
          - user-guide/search-browse.md
          - user-guide/teams.md
          - user-guide/profile.md
      - Moderator Features:
          - moderator-guide/overview.md
          - moderator-guide/answering-questions.md
          - moderator-guide/tagging.md
          - moderator-guide/moderation-queue.md
          - moderator-guide/presentation-mode.md
      - Admin Features:
          - admin-guide/overview.md
          - admin-guide/team-management.md
          - admin-guide/tag-management.md
          - admin-guide/roles-permissions.md
          - admin-guide/moderation-stats.md
          - admin-guide/audit-logging.md
          - admin-guide/export.md
  - Developer Guide:
      - Architecture:
          - architecture/system-design.md
          - architecture/database-schema.md
          - architecture/authentication.md
          - architecture/multi-tenancy.md
          - architecture/real-time.md
      - Security:
          - security/overview.md
          - security/rbac.md
          - security/content-moderation.md
          - security/audit-logging.md
          - security/security-headers.md
          - security/sessions.md
          - security/ci-scanning.md
          - security/rate-limiting.md
      - API Reference:
          - api/overview.md
          - api/authentication.md
          - api/questions.md
          - api/teams.md
          - api/tags.md
          - api/users.md
          - api/admin.md
      - Development:
          - development/setup.md
          - development/running-locally.md
          - development/testing.md
          - development/email-testing.md
          - development/migrations.md
          - development/code-style.md
          - development/code-review.md
          - development/contributing.md
  - Deployment:
      - deployment/docker-compose.md
      - deployment/production.md
      - deployment/environment.md
      - deployment/email-configuration.md
      - deployment/monitoring.md
  - About:
      - about/license.md
      - about/changelog.md
      - about/branding.md