name: Demo Reset

on:
  schedule:
    # Run daily at 6 AM UTC (2 AM EST, 11 PM PST)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  reset-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Reset demo instance
        run: |
          echo "🔄 Resetting demo instance..."
          
          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
            -X POST \
            -H "x-admin-key: ${{ secrets.DEMO_ADMIN_KEY }}" \
            -H "Content-Type: application/json" \
            https://api-demo.pulsestage.app/admin/reset-demo)
          
          http_status=$(echo "$response" | grep "HTTP_STATUS" | cut -d':' -f2)
          body=$(echo "$response" | sed '/HTTP_STATUS/d')
          
          echo "Response: $body"
          echo "HTTP Status: $http_status"
          
          if [ "$http_status" -eq 200 ]; then
            echo "✅ Demo reset successful!"
            exit 0
          else
            echo "❌ Demo reset failed with status $http_status"
            exit 1
          fi

