name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    
    # Only run for Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Auto-merge minor/patch updates
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # Use a PAT with repo scope - GITHUB_TOKEN doesn't have permission to approve PRs
          # For now, we'll just enable auto-merge without approval
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Only auto-merge minor and patch updates (as configured in dependabot.yml)
          target: minor
          # Approve the PR (will fail with GITHUB_TOKEN, but auto-merge will still work)
          approve: false
          # Command to pass to Dependabot (merge, squash, rebase)
          command: squash

